version: '3.3'
services:
  app-database:
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: HelloW0rld
    ports:
      - 33500:1234